### ISSUE TITLE
What sort of games do you like to play?

### ISSUE THREAD

**Issue by blainsmith** [mollikka/ama#10]
This includes video games, board games, card games, etc.

**Comment by mollikka** [comment]
These days I play video games primarily to socialize, since that seems to be the best way to keep up with some people. I like competitive games where we get to play as a team, like Counter-Strike and Dota. If I play alone I might play Civilization or puzzle games.

I'd like to play board games more, but I don't really have friends who would do that. I enjoy a game of Carcassonne whenever I get the chance, though.
