### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [mollikka/ama#14]

**Comment by mollikka** [comment]
At my university, I teach exercise sessions sometimes. (The professors give lectures, and more advanced students teach exercise sessions. I have no idea if that's how it works everywhere or not.)

I also like to help others with their homework whenever they ask, because it's a way for me to learn as well. It's not that I'm very good at everything people ask of me, but I like helping and figuring things out. Sometimes I might benefit from it more than the person I'm helping, even!
