### ISSUE TITLE
What's your favorite part about Python?

### ISSUE THREAD

**Issue by sindresorhus** [mollikka/ama#6]

**Comment by mollikka** [comment]
In high-level terms I think Python is a worthy language because it has a good power-per-keypress ratio but it's still extremely readable.

I guess my single favorite feature is _magic methods_. Something about writing those object.__add__(...) functions is just very satisfying. Probably because it's sometimes so obviously the right, idiomatic thing to do, you get less looming-refactor-depression while writing those parts. I can see why some feel it's backwards, but I just really like Pythonic magic methods.
