### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [mollikka/ama#8]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by mollikka** [comment]
I use cheap laptops for all my software dev needs. I like that I don't have to worry too much about carrying my machine around.

I appreciate being able to log into a new machine and work in a familiar environment ASAP. This is why I try to use few widespread general tools that the sysadmins have already installed rather than the latest and greatest. It also means I don't always get the same fonts. I really like Ubuntu Mono, so I use that if I can.

For programming my editor of choice right now is `vim`. For some reason I like to do quick edits (commit messages, config files...) in `nano`. If I have a graphical desktop environment loaded, it's `xfce4` and I just use the terminal emulator that comes bundled with that. And `zsh`-shell is the way to go, but I kind of envy the people who use fish-shell.

I just keep track of my tasks on Trello, write unit tests and code and try to exchange time into `git` commits. For now this works for me.
